spring:
  application:
    name: activityservice
  data:
    mongodb:
      uri: mongodb://localhost:27017/fitness_activity_db
server:
  port: 8082

logging:
  level:
    org.springframework.data.mongodb.core: DEBUG
    org.springframework.boot.autoconfigure.mongo: DEBUG
    com.fitness.activityservice: DEBUG